apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: {{ .Values.imagePullSecrets.name }}
  namespace: {{ .Values.namespace }}
data:
  .dockerconfigjson: {{ required "docker config 값이 없습니다." .Values.imagePullSecrets.dockerConfig | b64enc }}