apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.client.service.name }}
  namespace: {{.Values.namespace}}
spec:
  type: {{ .Values.client.service.type }}
  selector:
    app: {{ .Values.client.pod.label }}
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 80
