apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redis.service.name }}
  namespace: {{.Values.namespace}}
spec:
  type: {{ .Values.redis.service.type }}
  selector:
    app: {{ .Values.redis.pod.label }}
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
