apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.server.service.name }}
  namespace: {{.Values.namespace}}
spec:
  selector:
    app: {{ .Values.server.pod.label }}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
