apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.client.deployment.name }}
  namespace: {{.Values.namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.client.pod.label }}
  template:
    metadata:
      labels:
        app: {{ .Values.client.pod.label }}
    spec:
      containers:
        - name: {{ .Values.client.app.containerName }}
          image: {{.Values.client.image}}
          ports:
            - containerPort: 80
      {{- if .Values.client.imagePullSecretsName }}
      imagePullSecrets:
        - name: {{ .Values.client.imagePullSecretsName }}
      {{- end }}
