apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.server.service.name }}
  namespace: {{.Values.namespace}}
spec:
  type: {{ .Values.server.service.type }}
  selector:
    app: {{ .Values.server.pod.label }}
  ports:
    - port: 8080
      targetPort: 8080
